### ISSUE TITLE
TypeError: not all arguments converted during string formatting 

### ISSUE THREAD

**Issue by hoyeunglee** [caesar0301/treelib#80]
http://treelib.readthedocs.io/en/latest/examples.html 

it defined that it can use Object, but i pass tuple, it has error

>>> tree.create_node((0,0),(0,0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\treelib\node.py", line 142, in __repr__
    "tag=%r" % self.tag,
TypeError: not all arguments converted during string formatting

tree = Tree() 
#create root 
tree.create_node((0,0), "root") 
result = [aa[0]] 
previousnode = (0,0) 

>>> #create root 
... tree.create_node((0,0), "root") 
Traceback (most recent call last): 
  File "<stdin>", line 2, in <module> 
  File "C:\Python27\lib\site-packages\treelib\node.py", line 142, in __repr__ 
    "tag=%r" % self.tag, 
TypeError: not all arguments converted during string formatting

**Comment by caesar0301** [comment]
Fixed in commit 68b0f7df86c0edd432dbb5a9e4d933052c5ed981
